=== mmoruz/RoPsalt/roPsalt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="psalm">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="0" name="titles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="language" maxOccurs="unbounded"
                                            minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="red"/>
                                                </xs:sequence>
                                                <xs:attribute name="value"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="red">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i">
                                                  <xs:complexType mixed="true"/>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="i">
                                            <xs:complexType mixed="true"/>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="note">
                                            <xs:complexType mixed="true">
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="language">
                                                  <xs:complexType mixed="true">
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="red"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="value" type="xs:string"
                                                  use="optional" default="ro"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="sigle" type="xs:string" use="required"/>
                                    <xs:attribute name="language" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" ref="verse"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:short">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="151"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="verse">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="variant">
                    <xs:complexType mixed="true">
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="page">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="pageID" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="language">
                                <xs:complexType mixed="true">
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="i"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="note">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="language">
                                                  <xs:complexType mixed="true">
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="red"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="value" type="xs:string"
                                                  use="optional" default="ro"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="red"/>
                                    </xs:sequence>
                                    <xs:attribute name="value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="notations">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="paratext">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="dot">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="color" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sigle" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:short">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mmoruz/RoPsalt/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="psaltiri.css"?>
<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="roPsalt.xsd" id="1">
<titles><title sigle="PS" ><red>Ședeare 1. Î<i>n</i>tîi cî<i>n</i>tecul 1</red><note> Scris în josul paginii: <i>Întîi cîntecul 1</i>.</note></title>
<title sigle="PH" ><red>Şedearea 1</red>. <red>Cînteculu întăie oară</red><note> Scris: <language value="sla">ѡръ</language>.</note><red>e</red></title>
</titles><verse id="1">
<variant sigle="PS"><dot color="red"/><language value="ro"> <red>F</red>erice bărrbat ce nu mearrge la sfatul necuraților  </language><dot color="red"/><language value="ro"> și pre calea păcătoșilor nu stă  </language><dot color="red"/><language value="ro"> și la șederile pierdzătorilor nu șeade, </language><dot color="black"/></variant>
<variant sigle="PH"><language value="ro"><red>F</red>ericatu e bărbatu<i>l </i>carele nu mearse la svatulu necuraţiloruşi în calea greşiţiloru <note><language value="ro"> Scris:  </language><language value="sla">грѣшицилѡрꙋ</language><language value="ro">. </language></note> </language><language value="sla">не</language><language value="ro"> <note><language value="ro"> Slavon.: „nu”. </language></note> </language><language value="sla"></language><language value="ro"> stătuşi în scaunu pierdzătoriu nu şedzu, </language></variant>
<variant sigle="PG"><language value="lat">1. Beatus vir qui non abijt in consilio impiorum et in via peccatorum </language><page pageID=""/><language value="lat"> non stetit et in cathedra pestilentiae non sedit. </language></variant>
<variant sigle="PR"><language value="lat">1. Beatus vir qui non abijt in consilio impiorum </language><page pageID=""/><language value="lat"> et in via peccatorum non stetit: et in cathedra pestilentiae non sedit. </language></variant>
</verse>
<verse id="2">
<variant sigle="PS"><language value="ro"><red>C</red>e în leagea D[o]<i>m</i>nului învață- </language><page pageID="2"/><language value="ro"> se dzuoa și noaptea. </language></variant>
<variant sigle="PH"><language value="ro">Ce în leagea Domnului e voia luişi în leagea lui învaţă-se dzi <note><language value="ro"> Urmează: slavon. </language><language value="sla">и</language><language value="ro"> „şi”. </language></note> şi n[oa]pte <note><language value="ro"> Scris:  </language><language value="sla">н|птѣ</language><language value="ro">. </language></note>. </language></variant>
<variant sigle="PG"><language value="lat">2.Sed in lege domini voluntas eius: et in lege eius meditabitur die ac nocte. </language></variant>
<variant sigle="PR"><language value="lat">2. Sed in lege domini fuit voluntas eius: et in lege eius meditabitur die ac nocte. </language></variant>
</verse>
<verse id="3">
<variant sigle="PS"><dot color="black"/><language value="ro"> <red>Ș</red>i hi-va ca le<i>m</i>nul rrăsădi<i>t</i>lîngă ieșitu<i>l</i> apee[i] <note><language value="ro"> Scris: </language><language value="sla">а̑пе́е.</language><language value="ro"> </language></note>,  </language><dot color="red"/><language value="ro"> ce rrodu<i>l</i> său dă în vreamea sa,  </language><dot color="red"/><language value="ro"> și fru<i>n</i>dza lu<i>i</i> nu cade, și toată cîtă se face dospeaște. </language></variant>
<variant sigle="PH"><language value="ro">Şi fi-va ca e arburele răsădit la izvorritu<i>l</i> apeei,car[e]le poamele saledă-le în vreamea sa <red>ş</red>i frundza lui nu va cădeaşi toate <note><language value="ro"> Scris:  </language><language value="sla">тоатѣ</language><language value="ro">. </language></note> cît va face dospi-va. </language></variant>
<variant sigle="PG"><language value="lat">3.Et erit tanquam lignum quod plantatum est secus decursus aquarum: quod fructum suum dabit in tempore suo.4. Et folium eius non defluet: et omnia quaecumque fecerit prosperabuntur. </language></variant>
<variant sigle="PR"><language value="lat">3. Et erit tanquam lignum: quod plantatum est secus decursus aquarum. 4. Quod fructum suum dabit: in tempore suo. </language></variant>
</verse>
<verse id="4">
<variant sigle="PS"><dot color="red"/><language value="ro"> No așa, necuraților, no așa,  </language><dot color="red"/><language value="ro"> ce ca pulberea ce o mătoră vântu<i>l</i> den fața pământulu<i>i</i>. </language></variant>
<variant sigle="PH"><language value="ro"><red>N</red>u e aşea <note><language value="ro"> Scris deasupra rândului. </language></note>, necuraţii, nu e aşea,că e ca prahul cela ce-l mătură vîntul despre faţa pămîntului. </language></variant>
<variant sigle="PG"><language value="lat">5. Non sic impij non sic: sed tanquam puluis quem proijcit ventus a facie terrae. </language></variant>
<variant sigle="PR"><language value="lat">5. Et folium eius non decidet: et omnia quaecumque fecerit prosperabuntur. </language></variant>
</verse>
<verse id="5">
<variant sigle="PS"><dot color="red"/><language value="ro"> Dereptu acea nu vuru învie necurații la giude<i>ț</i>,  </language><dot color="red"/><language value="ro"> nece păcătoșii în sfatu<i>l</i> derepților, </language></variant>
<variant sigle="PH"><language value="ro">Dereptu acea nu voru <note><language value="ro"> Scris:  </language><language value="sla">вѡрꙋ.</language><language value="ro"> </language></note> învie necuraţii la giudeţu, nece greaşnicii în svatul pravednicilor. </language></variant>
<variant sigle="PG"><language value="lat">6. Ideo non resurgent impij in iudicio: neque peccatores in concilio iustorum. </language></variant>
<variant sigle="PR"><language value="lat">6. Non sic impij non sic: sed tanquam puluis quem proijcit ventus a facie terrae. </language></variant>
</verse>
<verse id="6">
<variant sigle="PS"><dot color="red"/><language value="ro"> Că ști[e] <note><language value="ro"> Scris:  </language><language value="sla">щѝ.</language><language value="ro"> </language></note> D[o]<i>m</i>nul calea derepți_ </language><page pageID="3"/><language value="ro"> lor,  </language><dot color="red"/><language value="ro"> și calea necuraților piere. </language></variant>
<variant sigle="PH"><language value="ro">Că şti Domnul calea pravednicilor şi calea necuraţilor peri-va. </language></variant>
<variant sigle="PG"><language value="lat">7. Quoniam novit dominus viam iustorum: et iter impiorum peribit. </language></variant>
<variant sigle="PR"><language value="lat">7. Ideo non resurgunt impij in iudicio: neque peccatores in concilio iustorum. </language></variant>
</verse>
<verse id="7">
<variant sigle="PR"><language value="lat">8. Quoniam novit dominus viam iustorum: et iter impiorum peribit. </language></variant>
</verse>
</psalm>

=== mmoruz/RoPsalt/132.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="psaltiri.css"?>
<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="roPsalt.xsd" id="132">
<titles><title sigle="CP1" ><language value="sla">пⷭ҇ѣ сте́пены</language>. Cîntecele spițelor 132</title>
<title sigle="CP1" ><language value="sla">пⷭ҇ѣ сте́пены</language>. Cîntecele spițelor 132</title>
<title sigle="CP2" ><language value="sla">пⷭ҇ѣ́ сте́пенїи</language>. Cîntecele spițelo<i>r</i> 132</title>
<title sigle="CP" ><red>Cîntecele spițelor • 132</red></title>
<title sigle="PC" ><language value="sla"><red>пⷭ҇ѣ́. степе́нїи</red></language><red> 132</red></title>
<title sigle="PS" ><red>C[în]te<i>ce</i> spițelo<i>r</i> 132</red></title>
<title sigle="PH" ><red>132</red></title>
<title sigle="PV" ><language value="sla"><red>пⷭ҇ѣ сⷫ҇ении рл҃в</red></language><red>. Cî<i>n</i>te<i>c</i>[e] 132</red></title>
<title sigle="PG" ><red>Canticum graduum. CXXXII</red></title>
<title sigle="PR" ><red>Canticum graduum. CXXXII</red></title>
</titles><verse id="1">
<variant sigle="CP1"><language value="sla">Сѐ нн҃ѣ что̀ до́бро илѝ что̀ кра́сно</language><language value="ro"> ++  </language><language value="sla">нѫ е̑же жи́ти бра́ти въкоу́пѣ</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Adecă acmu ce bine și ce e frumosu </language><language value="sla">··</language> <language value="ro">ce să vie frații depreună? </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Adecă acmu ce e bine și ce e frumo<i>s</i> </language><language value="sla">··</language> <language value="ro">ce să lăcuiască frații depreună? </language></variant>
<variant sigle="CP"><language value="ro"><red>•</red> <red>A</red>decă acmu ce e bine și ce e frumosu • ce să vie frații depreună? </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Adecă acmu ce e bine și ce e frumosu, </language><language value="sla">··</language> <language value="ro">ce să vie frații depreună! </language></variant>
<variant sigle="PS"><language value="ro"><red>A</red>decă acmu ce e bine și ce e frumo<i>s</i> <red>•</red> ce se vie frații depreună! </language></variant>
<variant sigle="PH"><language value="ro"><red>A</red>decă acmu ce e binre sau ce e frumo<i>s</i> numai se vie ca fraţi depreunră? </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>A</red>decă acmu ce e bire sau ce e frumosu, </language><language value="sla">··</language> <language value="ro"><red>c</red>e se vie frații depreună? </language></variant>
<variant sigle="PG"><language value="lat">1. Ecce quam bonum et quam iocundum: habitare fratres in vnum. </language></variant>
<variant sigle="PR"><language value="lat">1. Ecce quam bonum et quam iocundum: habitare fratres in vnum. </language></variant>
</verse>
<verse id="2">
<variant sigle="CP1"><language value="sla">ꙗ̑ко мӱрѡⷨ на гла́вѣ съхо́дѧщее на бра́дѫ</language><language value="ro"> ++  </language><language value="sla">бра́дѫ а҆а҆рѡнѧ</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Că mirul în cap ce deștinge în barbă, </language><language value="sla">··</language> <language value="ro">în barba lu Aaron, </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Că veșmîntul în cap, ce deștinge în barbă, </language><language value="sla">··</language> <language value="ro">în barba lu Aaro<i>n</i>, </language></variant>
<variant sigle="CP"><language value="ro">• Că mirul în cap, ce deștinge în barbă, • în barba lu Aaron. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Ca miru<i>l</i> în ca<i>p</i>, ce dești<i>n</i>ge în barbă, <note><language value="ro"> Scris cu negru: punctul care desparte textul slavonesc de cel românesc. </language></note> </language><language value="sla">··</language> <language value="ro">în barba lu A<i>a</i>ron, </language></variant>
<variant sigle="PS"><language value="ro"><red>•</red> Ca mirul în capu, ce deștinge în barbă, <red>•</red> în barba lu Arόn, </language></variant>
<variant sigle="PH"><language value="ro">Ca mirul pre capu<i>l</i> se deştingă pre barba, barba lu Aaro<i>n</i>, </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>C</red>a miru<i>l</i> spre capu ce deștinge îm barbă, </language><language value="sla">··</language> <language value="ro"><red>în</red> ba<i>r</i>ba lui Aron, </language></variant>
<variant sigle="PG"><language value="lat">2. Sicut vnguentum in capite: quod descendit in barbam </language><page pageID=""/><language value="lat"> barbam aaron. </language></variant>
<variant sigle="PR"><language value="lat">2. Sicut vnguentum in capite: quod descendit in barbam </language><page pageID=""/><language value="lat"> barbam aaron. </language></variant>
</verse>
<verse id="3">
<variant sigle="CP1"><language value="sla">съхо́дѧщее на ѡме́ты о҆де́ждѫ е̑го</language><language value="ro"> ++  </language><language value="sla">ꙗ̑ко роса̀ і҆е̑рмо́нскаа съхо́дѧщїа на го́ры сїѡ́нскыѧ</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> De deștingea în omet veșmîntul <note><language value="ro"> Scris:  </language><language value="sla">бе́шмѫтꙋль</language><language value="ro">. </language></note> lui, </language><language value="sla">··</language> <language value="ro">ca roa Ermonului, ce deștinse în codrii Sionului. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> De deștingea în omet veșmîntu<i>l</i> lui, </language><language value="sla">··</language> <language value="ro">ca roa Ermonului, ce deștinse în codrii Sionului. </language><language value="sla">··</language> <language value="ro"></language><page pageID="273r"/><language value="ro"> </language></variant>
<variant sigle="CP"><language value="ro">• De deștingea în omet veșmîntul lui, • ca roa Ermonului, ce deștinse în codrii Sionului. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> De deștingea în omet veșmî<i>n</i>tu<i>l</i> lui, </language><language value="sla">··</language> <language value="ro">ca roa Ermonulúi, ce deștinse în codrii Siónulu<i>i</i>. </language></variant>
<variant sigle="PS"><language value="ro"><red>•</red> De deștinge în ometu veșmîntu<i>l</i> lui, <red>•</red> ca rroao Ermonului, ce deștinse în codrii Sionului. </language></variant>
<variant sigle="PH"><language value="ro">Se deştingă pre tivitura veşmie[n]telor a lui. Ca rroa Iermonulu ce deştinge pre dealurile Sionului. </language></variant>
<variant sigle="PV"><language value="ro">Deștinge spre omătu veșmî<i>n</i>tu<i>l</i> lui, </language><language value="sla">··</language> <language value="ro"><red>c</red>a rrooa lui Errmonu ce deștinse spre codrii Siónu<i>l</i>[u]i. </language></variant>
<variant sigle="PG"><language value="lat">3. Quod descendit in oram vestimenti eius: sicut ros hermon qui descendit in montem sion. </language></variant>
<variant sigle="PR"><language value="lat">3. Quod descendit in oram vestimenti eius: sicut ros hermon qui descendit in montem sion. </language></variant>
</verse>
<verse id="4">
<variant sigle="CP1"><language value="sla">ꙗ̑ко тоу заповѣ́да г҃ь блⷭ҇венїе живо́ть до вѣ́ка</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Că aciia zise Domnul </language><page pageID="258v"/><language value="ro"> blagoslovire, viață pînă în veac. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Că aciia zise Domnul bl[a]goslovire, viață pînă în veac. </language></variant>
<variant sigle="CP"><language value="ro">• Că aciia zise Domnul blagoslovire, viață pînă în veac. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Că aciia zise Do<i>m</i>nu<i>l </i>bla_ </language><page pageID="152r"/><language value="ro"> goslovire, viața pînă în veac. </language></variant>
<variant sigle="PS"><language value="ro"><red>•</red> Că acie dzise D[om]nu<i>l</i> bl[ago]<i>s</i>[lo]vire, viiață pînă în v<i>ea</i>cu. </language></variant>
<variant sigle="PH"><language value="ro">Că acie dzise Dumnedzeu viaţă pănră în veacu. </language><page pageID="114v"/><language value="ro"> </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>C</red>ă aciia dzise D[o]mnu<i>l</i> bl[ago]<i>s</i>[lo]vire, viiață pără în veacu. </language></variant>
<variant sigle="PG"><language value="lat">4. Quoniam illic mandauit dominus benedictionem: et vitam vsque in saeculum. </language></variant>
<variant sigle="PR"><language value="lat">4. Quoniam illic mandauit dominus benedictionem: et vitam vsque in saeculum. </language></variant>
</verse>
</psalm>
