=== mmoruz/RoPsalt/roPsalt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="psalm">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="0" name="titles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="language" maxOccurs="unbounded"
                                            minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="red"/>
                                                </xs:sequence>
                                                <xs:attribute name="value"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="red">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i">
                                                  <xs:complexType mixed="true"/>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="i">
                                            <xs:complexType mixed="true"/>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="note">
                                            <xs:complexType mixed="true">
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="language">
                                                  <xs:complexType mixed="true">
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="red"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="value" type="xs:string"
                                                  use="optional" default="ro"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="sigle" type="xs:string" use="required"/>
                                    <xs:attribute name="language" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" ref="verse"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:short">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="151"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="verse">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="variant">
                    <xs:complexType mixed="true">
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="page">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="pageID" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="language">
                                <xs:complexType mixed="true">
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="i"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="note">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="language">
                                                  <xs:complexType mixed="true">
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="red"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="value" type="xs:string"
                                                  use="optional" default="ro"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="i"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="red"/>
                                    </xs:sequence>
                                    <xs:attribute name="value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="notations">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="paratext">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="dot">
                                <xs:complexType mixed="false">
                                    <xs:attribute name="color" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sigle" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:short">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mmoruz/RoPsalt/116.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="psaltiri.css"?>
<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="roPsalt.xsd" id="116">
<titles><title sigle="CP1" ><language value="sla">а̑ллилꙋїа</language>. 116</title>
<title sigle="CP1" ><language value="sla">а̑ллилꙋїа</language>. 116</title>
<title sigle="CP2" >Alliluia. 116} /239r</title>
<title sigle="CP" ><red>Alliluia • 116</red></title>
<title sigle="PC" ><red>Al<i>l</i>iluia</red><note> Scris în josul paginii: Al<i>l</i>iluia.</note> <red>116</red></title>
<title sigle="PS" ><red>Alli<i>l</i>[u]ia. 116</red></title>
<title sigle="PH" ><red>Cîntec[u] lu 116</red></title>
<title sigle="PV" ><red>116</red></title>
<title sigle="PG" ><red>HALELVIA. CXVI</red></title>
<title sigle="PR" ><red>HALELVIA. CXVI</red></title>
</titles><verse id="1">
<variant sigle="CP1"><language value="sla">Хвали́те г҃а въсѝ ѧзы́ци</language><language value="ro"> ++  </language><language value="sla">похва́лѝте е̑го въсѝ лю́дїи</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Lăudați Domnul toate limbile, </language><language value="sla">··</language> <language value="ro">prealăudați el toți oamenii. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Lăudați Domnul toate limbile, </language><language value="sla">··</language> <language value="ro">prealăudați-l toți oamenii. </language></variant>
<variant sigle="CP"><language value="ro"><red>•</red> <red>L</red>ăudați Domnul toate limbile, • prealăudați el toți oamenii. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Lăuda<i>ț</i>[i] Domnu<i>l</i> toate li<i>m</i>bile, </language><language value="sla">··</language> <language value="ro">prealău_ </language><page pageID="123r"/><language value="ro"> dați el toți oamenii. </language></variant>
<variant sigle="PS"><language value="ro"><red>L</red>ăudați D[om]nu<i>l</i> toate li<i>m</i>bile, prealăudați elu toți oaminii. </language></variant>
<variant sigle="PH"><language value="ro"><red>L</red>ăudaţi Domnulu toate limbile, mai lăudaţi-lu toţi oamenrii. </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>L</red>ăudați pre D[o]mnu<i>l</i> toate li<i>m</i>bili, </language><language value="sla">··</language> <language value="ro"><red>c</red>a<red> </red>lăudați însu<i>l</i> toți oamerii. </language></variant>
<variant sigle="PG"><language value="lat">1. Laudate dominum omnes gentes: laudate eum omnes populi. </language></variant>
<variant sigle="PR"><language value="lat">1. Laudate dominum omnes gentes: et collaudate eum omnes populi. </language></variant>
</verse>
<verse id="2">
<variant sigle="CP1"><language value="sla">ꙗ̑ко оутвръди́сѧ млⷭ҇ть е̑го на нⷭ҇а</language><language value="ro"> ++  </language><language value="sla">и̑ исти́на гнⷭ҇ѣ прѣбы́вае̑ть въ вѣ́кы</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Că întări-se milostea lui spre noi </language><language value="sla">··</language> <language value="ro">și deadevărul Domnului lăcuiaște în veac. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Că întări-se milostea sa spre noi </language><language value="sla">··</language> <language value="ro">și deadevărul Domnului lăcuiaște în veac. </language></variant>
<variant sigle="CP"><language value="ro">• Că întări-se milostea lui spre noi • și deadevărul Do<i>m</i>nului lăcuiaște în veac. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Că întări-se milóstea lui spre noi </language><language value="sla">··</language> <language value="ro">și deadevăru<i>l</i> Domnului lăcuiaște în vea<i>c</i>. </language></variant>
<variant sigle="PS"><language value="ro"><red>•</red> Că învîrtoșe-<i>s</i>[e] mesererea lui spre noi și deadeavăru<i>l</i> D[om]nului lăcu_ </language><page pageID="387"/><language value="ro"> iaște în veacu <note><language value="ro"> Urmează semnul „:”, scris cu negru. </language></note>. </language></variant>
<variant sigle="PH"><language value="ro">Că se învîrtoşe mila lui pre noi şi adevărul lui Dumnedzeu lăcui-va în veaci. </language><page pageID="101r"/><language value="ro"> </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>C</red>ă învîrtoșe-se meserearea lui spre noi </language><language value="sla">··</language> <language value="ro"><red>ș</red>i deadevăru<i>l</i> D[o]mnu<i>l</i>[u]i lăcuiaște <note><language value="ro"> Scris:  </language><language value="sla">лъкоуѫще</language><language value="ro">. </language></note> în veacu. </language></variant>
<variant sigle="PG"><language value="lat">2. Quoniam confirmata est super nos misericordia eius: et veritas domini manet in aeternum. </language></variant>
<variant sigle="PR"><language value="lat">2. Quoniam confirmata est super nos misericordia eius: et veritas domini manet in aeternum. </language></variant>
</verse>
</psalm>

=== mmoruz/RoPsalt/130.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="psaltiri.css"?>
<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="roPsalt.xsd" id="130">
<titles><title sigle="CP1" ><language value="sla">пⷭ҇ѣ степенїи</language>. Cîntecele spițelor 130</title>
<title sigle="CP1" ><language value="sla">пⷭ҇ѣ степенїи</language>. Cîntecele spițelor 130</title>
<title sigle="CP2" ><language value="sla">пⷭ҇ѣ́ степенїи</language>. Cîntecele spițelo<i>r</i> 130</title>
<title sigle="CP" ><red>Cîntecele spițelo<i>r</i> • 130 </red></title>
<title sigle="PC" ><language value="sla"><red>пⷭ҇ѣ́. степе́нїи</red></language><red>. 130</red></title>
<title sigle="PS" ><red>C[în]te<i>ce</i> spițelo<i>r</i></red><note> Urmează semnul „:”, scris cu roșu.</note><red> 130</red></title>
<title sigle="PH" ><red>Cîntarea 130</red></title>
<title sigle="PV" ><language value="sla"><red>пⷭ҇ѣ сте́пенїи</red></language><red>. 130</red></title>
<title sigle="PG" ><red>Canticum graduum. CXXX</red></title>
<title sigle="PR" ><red>Canticum graduum. CXXX</red></title>
</titles><verse id="1">
<variant sigle="CP1"><language value="sla">Ги҃ не възнⷭ҇есесѧ срⷣ҇це моѐ, нѝ възне́состѣсѧ о҆чи мои</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Doamne, nu rădică-se inema mea, nece înălțară-se ochii miei. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Doamne, nu rădică-se inima mea, nece înălțară-se ochii miei. </language></variant>
<variant sigle="CP"><language value="ro"><red>•</red> Doamne, nu rădică-se inema mea, nece înălțară-se ochii miei. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Doa<i>m</i>ne, nu rădicắ-se inema mea, nece se înălțară-se ochii miei. </language></variant>
<variant sigle="PS"><language value="ro"><red>D</red>[oam]ne, nu rădică-se înema me, ni<i>ci</i> înălțară-se ochii miei. </language></variant>
<variant sigle="PH"><language value="ro"><red>D</red>oamne, nu se înrălţă înrima mea, nece se înră[l]ţară ochii miei. </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>D</red>[oam]ne, nu sе rrădică înrema mea, </language><language value="sla">··</language> <language value="ro"><red>n</red>ece se înralță ochii miei <note><language value="ro"> Scris:  </language><language value="sla">мїе</language><language value="ro">. </language></note>. </language></variant>
<variant sigle="PG"><language value="lat">1. Domine non est exaltatum cor meum: neque elati sunt oculi mei. </language></variant>
<variant sigle="PR"><language value="lat">1. Domine non est exaltatum cor meum: neque elati sunt oculi mei. </language></variant>
</verse>
<verse id="2">
<variant sigle="CP1"><language value="sla">нѝ хѡ́диⷯ въ вели́кыⷯ нѝ въ ди́вныⷯ па́че ме́не</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Nece îmblaiu cu nalții, nece cu mai minunații de mine. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Nece îmblaiu întru mai marii, nece cu mai minunații de mine. </language></variant>
<variant sigle="CP"><language value="ro">• Nece îmblaiu cu înalții, nece cu mai minunații de mine. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Nece îmblaiu cu na<i>l</i>ții, nice cu mai-minunații </language><page pageID="149v"/><language value="ro"> de mene. </language></variant>
<variant sigle="PS"><language value="ro">• Nici îmblaiu cu înalți, ni<i>ci </i>cu mai minunații de mine. </language></variant>
<variant sigle="PH"><language value="ro">Nice îmblaiu mai în mari, nece în mai iudaţi de menre. </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>Nice îmblaiu </red>cu înralții, nice cu mai mirurații de mere. </language></variant>
<variant sigle="PG"><language value="lat">2. Neque ambulaui in magnis: neque in mirabilibus super me. </language></variant>
<variant sigle="PR"><language value="lat">2. Neque ambulaui in magnis: neque in mirabilibus super me. </language></variant>
</verse>
<verse id="3">
<variant sigle="CP1"><language value="sla">а̑ще не смѣрѣахсѧ не възнесохь дш҃ѫ моѫ</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Să nu </language><page pageID="256r"/><language value="ro"> plecaret mîndriia ce înălțară sufletul mieu, </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Că să nu mă plecai ce înălțai sufletu<i>l</i> mieu, </language></variant>
<variant sigle="CP"><language value="ro">• Să nu plecaret mîndriia ce înălțară sufletul mieu. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Să nu plecaret sufletu<i>l</i> mieu, </language><language value="sla">··</language> <language value="ro"></language></variant>
<variant sigle="PS"><language value="ro">• </language><page pageID="434"/><language value="ro"> Se nu plecare<i>t</i> mîndrriia, ce înălțaiu sufletu<i>l</i> mieu </language></variant>
<variant sigle="PH"><language value="ro">Se nu smerit înţeleşu, ce înrălţaiu sufletu<i>l</i> mieu. </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>S</red>e nu plecare tu mîndriia ce înralță sufletul mieu, </language></variant>
<variant sigle="PG"><language value="lat">3. Si non humiliter sentiebam: sed exaltaui animam meam. </language></variant>
<variant sigle="PR"><language value="lat">3. Si non humiliter sentiebam: sed exaltaui animam meam. </language></variant>
</verse>
<verse id="4">
<variant sigle="CP1"><language value="sla">ꙗ̑ко ѿдое́нѡе на мт҃е́рь своѫ</language><language value="ro"> ++  </language><language value="sla">ꙗ̑ко възда́си на дш҃ѫ моѫ</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Ca băiatul spre mumă-sa, </language><language value="sla">··</language> <language value="ro">că da-veri spre sufletul mieu. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Ca băiatul spre mumă-sa, </language><language value="sla">··</language> <language value="ro">că da-veri spre sufletul mieu. </language></variant>
<variant sigle="CP"><language value="ro">• Ca băiatul spre mumă-sa, • că da-veri spre sufletul mieu. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Ca băiatu<i>l</i> spre mumă-sa, </language><language value="sla">··</language> <language value="ro"><red>c</red>ă da-veri spre sufletu<i>l </i>mieu. </language></variant>
<variant sigle="PS"><language value="ro">• Ca băiatul spre ma-sa, <red>•</red> că da-veri spre sufletu<i>l</i> mieu. </language></variant>
<variant sigle="PH"><language value="ro">Ca aplecatul cătră mumă-sa, că veri da pre sufletu<i>l</i> mieu. </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>C</red>a sugătoriu<i>l</i> spre maică-sa, </language><language value="sla">··</language> <language value="ro"><red>c</red>ă veri da spre sufletu<i>l</i> mieu. </language></variant>
<variant sigle="PG"><language value="lat">4. Sicut ablactatus est super matre sua: ita retributio in anima mea. </language></variant>
<variant sigle="PR"><language value="lat">4. Sicut ablactatus super matre sua: ita retribues in animam meam. </language></variant>
</verse>
<verse id="5">
<variant sigle="CP1"><language value="sla">да оу̑повае̑ть і҆ил҃ь на г҃а, ѿни́нѣ́ и̑ дѡ вѣка</language><language value="ro"> ++  </language></variant>
<variant sigle="CP1"><language value="sla">··</language><language value="ro"> Să upovăiască I[sra]il spre Domnul de acmu pînă în veac. </language></variant>
<variant sigle="CP2"><language value="sla">··</language><language value="ro"> Să upovăiască I[sra]il spre </language><page pageID="270v"/><language value="ro"> Domnul, de acmu și pînă în veac. </language></variant>
<variant sigle="CP"><language value="ro">• Să upovăiască Israil spre Domnul, de acmu pînă în veac. </language></variant>
<variant sigle="PC"><language value="sla">··</language><language value="ro"> Să upovăiască I[zra]il spre Do<i>m</i>nul de acmu pînă în veac! </language></variant>
<variant sigle="PS"><language value="ro">• Să upuvăiască Is[rai]l spre D[om]nu<i>l</i>, de acmu pînă în veacu. </language></variant>
<variant sigle="PH"><language value="ro">Se nedejdească Israil pre Dumnedzeu de acmu şi pără în veac. </language></variant>
<variant sigle="PV"><language value="sla">··</language><language value="ro"> <red>S</red>e nedejduiască creștiru<i>l</i> spre D[om]<i>n</i>u<i>l</i> </language><language value="sla">··</language> <language value="ro"><red>d</red>e acmu pără în veac. </language></variant>
<variant sigle="PG"><language value="lat">5. Speret israel in domino: ex hoc nunc et vsque in saeculum. </language></variant>
<variant sigle="PR"><language value="lat">5. Speret israel in domino: ex hoc nunc et vsque in saeculum. </language></variant>
</verse>
</psalm>
